      - name: Deploy to Modal
        shell: bash
        env:
          MODAL_PROFILE: ${{ env.MODAL_PROFILE }}
          MODAL_ENTRYPOINT: ${{ env.MODAL_ENTRYPOINT }}
        run: |
          set -euo pipefail
          echo "Using MODAL_PROFILE=${MODAL_PROFILE}"
          echo "Deploying entrypoint: ${MODAL_ENTRYPOINT}"

          # Confirm CLI version
          python -m modal --version || true

          # Show if any --profile is sneaking in from env/aliases
          echo "Searching for stray --profile flags in repo..."
          grep -R --line-number -- '--profile' || true

          # The only allowed command (NO --profile on deploy):
          CMD=(python -m modal deploy "${MODAL_ENTRYPOINT}")
          echo "+ ${CMD[@]}"

          for attempt in 1 2 3; do
            if env -u MODAL_TOKEN_ID -u MODAL_TOKEN_SECRET "${CMD[@]}"; then
              echo "Deploy succeeded."
              exit 0
            fi
            echo "Deploy failed (attempt ${attempt}). Retrying in 10s..."
            sleep 10
          done

          echo "::error::Modal deploy failed after 3 attempts."
          exit 1
