name: Modal Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'modal/**'
      - '.github/workflows/modal-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Modal CLI
        run: |
          python -m pip install --upgrade pip
          pip install modal-client Pillow moviepy supabase

      - name: Deploy to Modal
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: |
          modal deploy modal/modal_app.py
