name: Modal Deploy
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'modal/**'
      - '.github/workflows/modal-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Modal CLI + deps
        run: |
          python -m pip install --upgrade pip
          # Install the CLI-capable package
          python -m pip install "modal>=0.56" Pillow==10.3.0 moviepy==1.0.3 supabase==2.4.3
          # Sanity checks
          python -c "import modal; print('modal version:', getattr(modal,'__version__','?'))"
          python -m modal --help > /dev/null

      - name: Deploy to Modal
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: |
          python -m modal deploy modal/modal_app.py
