name: Modal Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main, master, develop ]
    paths:
      - "modal/**"
      - "modal_app.py"
      - ".github/workflows/modal-deploy.yml"

concurrency:
  group: modal-deploy-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.11"
  MODAL_ENTRYPOINT: "modal/modal_app.py"  # change if your entry file is elsewhere
  MODAL_PROFILE: "prod"                   # single source of truth for profile

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('requirements-ci.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-

      - name: Install Modal CLI (runner-only)
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements-ci.txt ]; then
            pip install -r requirements-ci.txt
          else
            pip install "modal>=1.1,<2"
          fi
          python -m modal --version >/dev/null

      # --- Modal auth (writes to named profile, then verifies by reading ~/.modal.toml) ---
      - name: Configure Modal token
        shell: bash
        env:
          CI_MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          CI_MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
          MODAL_PROFILE: prod
        run: |
          set -euo pipefail

          if [ -z "${CI_MODAL_TOKEN_ID:-}" ] || [ -z "${CI_MODAL_TOKEN_SECRET:-}" ]; then
            echo "::error::Missing MODAL_TOKEN_ID or MODAL_TOKEN_SECRET in repo secrets."
            exit 1
          fi

          # Write creds into the prod profile (no MODAL_* env exported)
          python -m modal token set \
            --token-id "$CI_MODAL_TOKEN_ID" \
            --token-secret "$CI_MODAL_TOKEN_SECRET" \
            --profile "$MODAL_PROFILE"

          # Sanity check: verify ~/.modal.toml has prod profile with keys
          python - <<EOF
import sys, pathlib
p = pathlib.Path.home() / ".modal.toml"
if not p.exists():
    print("::error::~/.modal.toml not found after token set")
    sys.exit(1)
import tomllib
try:
    data = tomllib.loads(p.read_text())
except Exception as e:
    print(f"::error::Failed to parse ~/.modal.toml: {e}")
    sys.exit(1)
prod = data.get("prod") or {}
tid = prod.get("token_id")
ts  = prod.get("token_secret")
if not (tid and ts):
    print("::error::Missing token_id or token_secret in [prod] profile")
    sys.exit(2)
print(f"Modal token appears set for profile 'prod' (token_id length={len(tid)})")
sys.exit(0)
EOF

          # Make profile visible to subsequent steps
          echo "MODAL_PROFILE=$MODAL_PROFILE" >> "$GITHUB_ENV"

          # IMPORTANT: never echo secrets; clear env
          unset CI_MODAL_TOKEN_ID CI_MODAL_TOKEN_SECRET

      - name: Validate entrypoint exists
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f "$MODAL_ENTRYPOINT" ]; then
            echo "::error file=$MODAL_ENTRYPOINT::Modal entrypoint not found"
            exit 1
          fi

      # --- Deploy (with retry) ---
      - name: Deploy to Modal
        shell: bash
        env:
          MODAL_PROFILE: ${{ env.MODAL_PROFILE }}
          MODAL_ENTRYPOINT: ${{ env.MODAL_ENTRYPOINT }}
        run: |
          set -euo pipefail
          echo "Using MODAL_PROFILE=${MODAL_PROFILE}"
          echo "Deploying entrypoint: ${MODAL_ENTRYPOINT}"

          for attempt in 1 2 3; do
            if env -u MODAL_TOKEN_ID -u MODAL_TOKEN_SECRET \
              python -m modal deploy "${MODAL_ENTRYPOINT}" --profile "${MODAL_PROFILE}"; then
              echo "Deploy succeeded."
              exit 0
            fi
            echo "Deploy failed (attempt ${attempt}). Retrying in 10s..."
            sleep 10
          done

          echo "::error::Modal deploy failed after 3 attempts."
          exit 1

      # ================= Alerts on failure (email + SMS) =================
      - name: Send failure email (Resend)
        if: failure()
        shell: bash
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          ALERT_EMAIL_FROM: ${{ secrets.ALERT_EMAIL_FROM }}
          ALERT_EMAIL_TO: ${{ secrets.ALERT_EMAIL_TO }}
        run: |
          set -euo pipefail
          # Skip if any required secret is missing
          [ -n "${RESEND_API_KEY:-}" ] && [ -n "${ALERT_EMAIL_FROM:-}" ] && [ -n "${ALERT_EMAIL_TO:-}" ] || exit 0

          RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          MSG_SUBJECT="❌ Modal deploy failed: ${GITHUB_REPOSITORY}@${GITHUB_REF_NAME}"
          MSG_TEXT="Workflow failed. Commit: ${GITHUB_SHA::7}\nRun: ${RUN_URL}\nBranch: ${GITHUB_REF_NAME}"
          BODY=$(jq -nc --arg from "$ALERT_EMAIL_FROM" --arg to "$ALERT_EMAIL_TO" --arg subject "$MSG_SUBJECT" --arg text "$MSG_TEXT" \
            '{from:$from,to:[$to],subject:$subject,text:$text}')

          curl -s -X POST https://api.resend.com/emails \
            -H "Authorization: Bearer ${RESEND_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "${BODY}"

      - name: Send failure SMS (Twilio)
        if: failure()
        shell: bash
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          ALERT_SMS_TO: ${{ secrets.ALERT_SMS_TO }}
        run: |
          set -euo pipefail
          # Skip if any required secret is missing
          [ -n "${TWILIO_ACCOUNT_SID:-}" ] && [ -n "${TWILIO_AUTH_TOKEN:-}" ] && [ -n "${TWILIO_FROM:-}" ] && [ -n "${ALERT_SMS_TO:-}" ] || exit 0

          RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          MSG="❌ Modal deploy failed: ${GITHUB_REPOSITORY}@${GITHUB_REF_NAME} (${GITHUB_SHA::7}) ${RUN_URL}"
          curl -s -X POST "https://api.twilio.com/2010-04-01/Accounts/${TWILIO_ACCOUNT_SID}/Messages.json" \
            --data-urlencode "From=${TWILIO_FROM}" \
            --data-urlencode "To=${ALERT_SMS_TO}" \
            --data-urlencode "Body=${MSG}" \
            -u "${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}"
